### PR TITLE
Added procedure to get current world directory.

### LINKED ISSUE #55: World Directory (Builds upon #32).
### Feature description

It builds upon #32.

There's the "Get current world's name" procedure, which I'm guessing came from #32. But it doesn't really get the worlds directory and solve the issue they described.
Yes, you can get it by using "Get the game directory" then add "/saves/" then the world name. But it's not really good, specially as that only solves it for when the mod is used in Singleplayer.

I'm trying to place world specific configs, so in the "serverconfig" directory.

It would be very nice if it got the entire path directly, it would solve if the server and client files are in the same directory, as it is in MCreator. If a world is named the same for singleplayer and multiplayer, the IF statement is gonna go for the first one that is true, but it might not even be the one that's in use.

But it would *maybe* also solve the issue when people create new worlds without naming them, since they get named "New world (N)" in the directory.
Right now it'll always just be named "New world" so no matter how many "New world (N)" it's always going to go for the first one made.

Maybe I'm just missing something, but I've gone through all the blocks and can't find a way to make it work as needed.

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my feature request <a href='https://github.com/Goldorion/File-Manager-MCreator/issues?q=is%3Aissue' target='_blank'>is not already suggested</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

### PR DESCRIPTION
**Pull request by Rinnray**
This *should* possibly fix #55. It just crashes when ran with something like "Player right click block" trigger. Might not be this code but just things in general.

Not a Java programmer so please tripple check 😅

### CODE REVIEW

**Comment by Goldorion** [comment]
Your code will simply not work.

**Comment by Rinnray** [comment]
🤨 Care to elaborate? Because testing things out it, works. It gets the correct world folder and creates a file in there as wanted.

**Comment by Rinnray** [comment]
> Your code will simply not work.

So I *really* don't get why this.
Tested both in MCreator and outside in a normal environment and it *does* simply just work.

**Comment by Goldorion** [comment]
> world.isClientSide() ? Minecraft.getInstance().getSingleplayerServer()

If the code is executed on the client side, it gets the single player server, no matter what. What will happens on a multiplayer server? It's not single player... so it's null.

**Comment by Rinnray** [comment]
Ooooh, I see. Thank you.

**Pull request closed without merging**
